name = "lms-crud-worker"
main = "index.js"
compatibility_date = "2026-06-25"

[[d1_databases]]
binding = "DB" # Harus sama dengan env.DB di kode
database_name = "lms"
database_id = "PASTE_DATABASE_ID_YANG_ANDA_SALIN_TADI"

[vars]
JWT_SECRET = "rahasia-lms-super-aman-2026"
